#!/bin/bash

rm work-obj93.cf # Ta bort gamla objectfilen

# Kompilera alla componenter, ieee=mentor option is for non standard lirary
ghdl -a --std=02 --ieee=synopsys *.vhd

# Kör skiten
ghdl -r fsm --vcd=wave_fsm.vcd --stop-time=100ns
