#!/bin/bash

rm work-obj93.cf # Ta bort gamla objectfilen

# Kompilera alla componenter, samt tb
ghdl -a full_adder.vhd AdderBlock.vhd multiplier.vhd multiplier_tb.vhd 

# Kör skiten
ghdl -r multiplier_tb --vcd=multiplier_tb.vcd --stop-time=440ns